/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-13 03:11:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import qna.model.vo.MyQna;
import java.util.*;
import member.model.vo.Member;

public final class mypageQnA_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/mypage/mypageHead.jsp", Long.valueOf(1552436651626L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1551750544000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("qna.model.vo.MyQna");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<MyQna> myqnaList = (ArrayList<MyQna>)request.getAttribute("myqnaList");
	int listCount = ((Integer)request.getAttribute("listCount")).intValue();
	int startPage = ((Integer)request.getAttribute("startPage")).intValue();
	int endPage = ((Integer)request.getAttribute("endPage")).intValue();
	int maxPage = ((Integer)request.getAttribute("maxPage")).intValue();			
	int currentPage = ((Integer)request.getAttribute("currentPage")).intValue();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t");
      out.write('\r');
      out.write('\n');

	Member loginMember = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>신통시장</title>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<link href=\"/semi/resources/images/favicon.png\" rel=\"icon\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/semi/vendor/bootstrap/css/bootstrap.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/semi/resources/css/common.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/semi/resources/css/mypage.css\" />\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/semi/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/semi/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- Navigation -->\r\n");
      out.write("\t\t<header class=\"myHeader\">\r\n");
      out.write("\t\t\t<div class=\"t_nav\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<!-- 로그인 전 -->\r\n");
      out.write("\t\t\t\t\t");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/semi/views/member/login.jsp\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/semi/views/member/register.jsp\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#;\">장바구니</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/semi/views/member/login.jsp\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<!-- 로그인 전 -->\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 로그인 후 -->\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/semi\">홈</a></li>\r\n");
      out.write("\t\t\t\t\t<li><span class=\"user\">");
      out.print( loginMember.getMemName() );
      out.write("</span>님 안녕하세요!</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/semi/logout\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#;\">장바구니</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/semi/myinfo?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<!-- 로그인 후 -->\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"mypageTop\">\r\n");
      out.write("\t\t\t\t<div class=\"topCon\">\r\n");
      out.write("\t\t\t\t\t<h2>마이페이지</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"myContent\">\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\" id=\"mypage_nav\">\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"/semi/myinfo?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("\" id=\"nav_list\">내정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/views/mypage/mypageUpdateInfo.jsp\" id=\"nav_list\">개인정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/pointlist?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("\" id=\"nav_list\">적립금</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/couponlist?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("\" id=\"nav_list\">쿠폰</a></li>\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/myqna?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("&page=1\" id=\"nav_list\">내가 쓴 QnA</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/semi/mypreview?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("&page=1\" id=\"nav_list\">내가 쓴 후기</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t// answer box 슬라이드\r\n");
      out.write("\t\t\t\t$('.aBox').hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('.qBox').click(function(){\r\n");
      out.write("\t\t\t\t\t$('.aBox').slideUp(300);\r\n");
      out.write("\t\t\t\t\tif(!$(this).siblings('.aBox').is(':visible')){\r\n");
      out.write("\t\t\t\t\t\t$(this).siblings('.aBox').slideDown(300);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//삭제 alert\r\n");
      out.write("\t\t\t\t$(\".btDelete\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar message = confirm(\"정말로 삭제하시겠습니까?\\n삭제한 글은 되돌릴 수 없습니다.\");\r\n");
      out.write("\t\t\t\t\tif(message){\r\n");
      out.write("\t\t\t\t\t\talert(\"글이 정상적으로 삭제되었습니다!\");\r\n");
      out.write("\t\t\t\t\t\tlocation.replace('/semi/qnadel?no=' + $(this).attr('value') + '&userid=' + $(this).attr('data-value'));\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"container myContainer\">\r\n");
      out.write("\t\t\t<div id=\"list_name\">내가 쓴 QnA(");
      out.print( listCount );
      out.write(")</div>\r\n");
      out.write("\t\t\t<div><a href=\"\">QnA 글 작성하기</a></div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<th>답변상태</th>\r\n");
      out.write("\t\t\t\t\t\t<th>QnA 내용</th>\r\n");
      out.write("\t\t\t\t\t\t<th>관리</th>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
 if(myqnaList.size() == 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=3 class=\"noList\">작성한 QnA가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 for(MyQna myqna : myqnaList){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print( myqna.getmQnaNo() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t <td width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t \t");
 if(myqna.getQnaAnsYn().equals("Y")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \t<p class=\"aDone\">답변완료</p>\r\n");
      out.write("\t\t\t\t\t\t\t \t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \t<p class=\"aYet\">답변대기</p>\r\n");
      out.write("\t\t\t\t\t\t\t \t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t\t\t\t <td width=\"70%\">\r\n");
      out.write("\t\t\t\t\t\t\t \t<div class=\"qBox\">\r\n");
      out.write("\t\t\t\t\t\t\t \t\t<div class=\"mark\">Q</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t<div class=\"head\">\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t\t<span>");
      out.print( myqna.getmQnaTitle() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t\t<span>");
      out.print( myqna.getQnaQid() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t\t<span>");
      out.print( myqna.getmQnaDate() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t\t");
      out.print( myqna.getQnaQContent() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t");
 if(myqna.getQnaAnsYn().equals("Y")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \t<!-- <div class=\"contentBox\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t \t<div class=\"aBox\">\r\n");
      out.write("\t\t\t\t\t\t\t \t\t<div class=\"mark\">A</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t\t");
      out.print( myqna.getQnaAContent() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t<!-- </div> -->\r\n");
      out.write("\t\t\t\t\t\t\t \t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t\t\t\t <td width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t \t");
 if(myqna.getQnaAnsYn().equals("N")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \t<p><a href=\"/semi/myqnaview?pqnum=");
      out.print( myqna.getmQnaNo() );
      out.write("&page=");
      out.print( currentPage );
      out.write("\" class=\"btModify\">수정</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t \t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \t<p><button name=\"delno\" data-value=\"");
      out.print( myqna.getQnaQid() );
      out.write("\" value=\"");
      out.print( myqna.getmQnaNo() );
      out.write("\" class=\"btDelete\">삭제</button></p>\r\n");
      out.write("\t\t\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Paging 처리 -->\r\n");
      out.write("\t\t\t\t<nav aria-label=\"Page navigation example\">\r\n");
      out.write("\t\t\t\t  <ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t  \t<!-- 이전 -->\r\n");
      out.write("\t\t\t\t    <li class=\"page-item\">\r\n");
      out.write("\t\t\t\t   \t");
 if((currentPage - 5) < startPage && (currentPage - 5) > 1){ 
      out.write("\r\n");
      out.write("\t\t\t\t      <a class=\"page-link\" href=\"/semi/myqna?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("&page=");
      out.print( startPage - 5 );
      out.write("\" aria-label=\"Previous\">\r\n");
      out.write("\t\t\t\t        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t        <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t    ");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t      <a class=\"page-link\" aria-label=\"Previous\">\r\n");
      out.write("\t\t\t\t        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("\t\t\t\t        <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t   \t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <!-- //이전 -->\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t   <!-- 페이지 -->\r\n");
      out.write("\t\t\t\t    ");
 for(int p = startPage; p <= endPage; p++){ 
				    	if(p == currentPage){
				    
      out.write("\r\n");
      out.write("\t\t\t\t    <li class=\"page-item active\">\r\n");
      out.write("\t\t\t\t    \t<a class=\"page-link\" >");
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"page-link\" href=\"/semi/myqna?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("&page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t");
 }} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--// 페이지 -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 다음 -->\r\n");
      out.write("\t\t\t\t    <li class=\"page-item\">\r\n");
      out.write("\t\t\t\t   ");
 if((currentPage + 5) > endPage && (currentPage + 5) < maxPage){ 
      out.write("\r\n");
      out.write("\t\t\t\t      <a class=\"page-link\" href=\"/semi/myqna?mem_userid=");
      out.print( loginMember.getMemUserid() );
      out.write("&page=");
      out.print( endPage + 5 );
      out.write("\" aria-label=\"Next\">\r\n");
      out.write("\t\t\t\t        <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t        <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t    ");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t      <a class=\"page-link\" aria-label=\"Next\">\r\n");
      out.write("\t\t\t\t        <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("\t\t\t\t        <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t    ");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t    <!-- //다음 -->\r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<footer class=\"py-5 bg-dark\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t  <p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2019</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </footer>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
